app:
  title: "TB Isolation Cost Calculator"
  description: "Streamlit-based simulation tool for tuberculosis (TB) isolation scenarios."

simulation_models:
  - id: "models.tb_isolation"
    name: "TB Isolation"
    #todo, example
  - id: "models.network_seir"
    name: "Network SEIR"
    #todo, example
  - id: "models.measles_school"
    name: "Measles in Schools"

#default_parameters:
#  Number of contacts for each released TB case: 141.5
#  Probability that contact develops latent TB if 14-day isolation: 0.02
#  Multiplier for infectiousness with 5-day vs. 14-day isolation: 1.5
#  Ratio of workdays to total days: 0.714
#  prob_latent_to_active_2yr: 0.05
#  prob_latent_to_active_lifetime: 0.05
#  cost_latent: 300.0
#  cost_active: 34523.0
#  isolation_cost: 85.0
#  discount_rate: 0.03
#  remaining_years: 40
#  hourly_wage_worker: 29.36

#latest
default_parameters:
  Number of contacts for each released TB case: 141.5
  Probability that contact develops latent TB if 14-day isolation: 0.02
  Multiplier for infectiousness with 5-day vs. 14-day isolation: 1.5
  Ratio of workdays to total days: 0.714

  Probability of transitioning from latent to active TB:
    First 2 years (prob_latent_to_active_2yr): 0.05
    Rest of lifetime (prob_latent_to_active_lifetime): 0.05

  Costs:
    Cost of latent TB infection (cost_latent): 300.0
    Cost of active TB infection (cost_active): 34523.0
    Isolation type (1=hospital,2=motel,3=home): 3
    Daily isolation cost (isolation_cost): 85.0
    Direct medical cost of a day of isolation: 3996.0
    Cost of motel room per day: 150.0
    Hourly wage for worker: 29.36
    Hourly wage for nurse: 42.42
    Time for nurse to check in w/ pt in motel or home (hrs): 2
    Hourly wage for public health worker: 40.0

  Discount rate: 0.03
  Remaining years of life: 40

