"""
Reads app.py and the supporting utils/, config/, styles/, models/, selected/
directories and writes a self-contained stlite index.html that runs the whole
app in the browser via Pyodide/WASM.

Usage (called by `make build-html`):
    python scripts/build_index.py \
        --app  app.py \
        --out  build/index.html \
        --css  https://cdn.jsdelivr.net/npm/@stlite/browser@0.85.1/build/stlite.css \
        --js   https://cdn.jsdelivr.net/npm/@stlite/browser@0.85.1/build/stlite.js \
        --title "EpiCON Cost Calculator"
"""

from __future__ import annotations

import argparse
import json
import re
import tomllib
from pathlib import Path

def _extract_requirements(pyproject: Path) -> list[str]:
    """
    Read [project.dependencies] from pyproject.toml and return bare package
    names for stlite's requirements list.
    Streamlit itself is already bundled in stlite and must be omitted.
    """
    SKIP = {"streamlit"}
    if not pyproject.exists():
        return []

    with pyproject.open("rb") as fh:
        data = tomllib.load(fh)

    deps: list[str] = data.get("project", {}).get("dependencies", [])
    result: list[str] = []
    for dep in deps:
        name = re.split(r"[>=<!;\[]", dep)[0].strip()
        if name.lower() not in SKIP and name:
            result.append(name)
    return result


def _read_source_files(app_py: Path) -> dict[str, str]:
    """
    Return {relative_path: file_contents} for every file stlite needs to
    mount into Pyodide's virtual filesystem.

    Directories collected (relative to repo root):
        app.py
        utils/      — core Python utilities
        config/     — YAML app/path config files
        styles/     — CSS files (optional)
        models/     — Python model files (optional)
        selected/   — curated model subset (optional)
        examples/   — example YAML models (optional)
    """
    root = app_py.parent
    files: dict[str, str] = {}

    # entry-point
    files[app_py.name] = app_py.read_text(encoding="utf-8")

    # directories to bundle
    dirs_to_include = [
        root / "utils",
        root / "config",
        root / "styles",
        root / "models",
        root / "selected",
        root / "examples",
    ]

    extensions = {".py", ".yaml", ".yml", ".css", ".json", ".md"}

    for directory in dirs_to_include:
        if not directory.is_dir():
            continue
        for f in sorted(directory.rglob("*")):
            if f.is_file() and f.suffix in extensions:
                rel = f.relative_to(root).as_posix()
                try:
                    files[rel] = f.read_text(encoding="utf-8")
                except UnicodeDecodeError:
                    pass  # skip binary files

    return files


def _build_html(
    *,
    title: str,
    css_url: str,
    js_url: str,
    entrypoint: str,
    requirements: list[str],
    files: dict[str, str],
) -> str:
    files_json = json.dumps(files, ensure_ascii=False, indent=4)
    req_json   = json.dumps(requirements, ensure_ascii=False)

    return f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <title>{title}</title>
    <link rel="stylesheet" href="{css_url}" />
    <!--
      EpiCON Cost Calculator — stlite (Streamlit on WebAssembly)
      Generated by scripts/build_index.py — do not edit by hand.
      Re-generate with: make build-html
    -->
  </head>
  <body>
    <div id="root"></div>
    <script type="module">
      import {{ mount }} from "{js_url}";

      mount(
        {{
          requirements: {req_json},
          entrypoint: "{entrypoint}",
          files: {files_json},
        }},
        document.getElementById("root"),
      );
    </script>
  </body>
</html>
"""

# CLI

def main() -> None:
    parser = argparse.ArgumentParser(description="Generate stlite index.html")
    parser.add_argument("--app",   required=True, help="Path to app.py")
    parser.add_argument("--out",   required=True, help="Output index.html path")
    parser.add_argument("--css",   required=True, help="stlite CSS CDN URL")
    parser.add_argument("--js",    required=True, help="stlite JS CDN URL")
    parser.add_argument("--title", default="EpiCON Cost Calculator")
    args = parser.parse_args()

    app_py    = Path(args.app).resolve()
    out       = Path(args.out)
    pyproject = app_py.parent / "pyproject.toml"

    requirements = _extract_requirements(pyproject)
    files        = _read_source_files(app_py)

    html = _build_html(
        title        = args.title,
        css_url      = args.css,
        js_url       = args.js,
        entrypoint   = app_py.name,
        requirements = requirements,
        files        = files,
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(html, encoding="utf-8")
    print(f"Written: {out}  ({len(html):,} bytes, {len(files)} files mounted)")
    if requirements:
        print(f"Pyodide packages: {', '.join(requirements)}")


if __name__ == "__main__":
    main()
